apiVersion: v2
name: bookinfo
description: Istio bookinfo app
type: application
version: 0.2.3
appVersion: "1.16.2"
icon: http://git.rfed.me/gitea/catalog_demo/raw/branch/main/charts/bookinfo/Istio-bluelogo-nobackground-unframed.svg
maintainers:
  - name: Rancher
    url: https://github.com/rancher
