wordpress:
  wordpressEmail: user@example.com
  wordpressUsername: user
  wordpressPassword: ""
  service:
    type: ClusterIP

  persistence:
    enabled: true
    size: 1Gi

  ingress:
    enabled: true
    hostname: wordpress.rfed.me
    ingressClassName: nginx
  externalDatabase:
    host: localhost
    port: 3306
    user: bn_wordpress
    password: ""
    database: bitnami_wordpress
    existingSecret: ""
  mariadb:
    enabled: true
    auth:
      rootPassword: ""
      database: bitnami_wordpress
      username: bn_wordpress
      password: ""
    primary:
      persistence:
        enabled: false
        size: 8Gi
