apiVersion: v2
name: quake-kube
description: Quake 3 Arena in a browser
type: application
version: 0.2.3
appVersion: "v1.0.7"
icon: http://git.rfed.me/gitea/catalog_demo/raw/branch/main/charts/quake-kube/Quake_III_Arena_Logo.svg
maintainers:
  - name: Rancher
    url: https://github.com/rancher
